version: "3.8"

services:
  postgres:
    image: ${COMPOSE_PROJECT_NAME}_postgres_dev
    container_name: ${COMPOSE_PROJECT_NAME}_postgres_dev
    build:
      context: ./docker/postgres
    restart: always
    env_file:
      - .env
      - dev.env
    volumes:
      - type: volume
        source: postgres_volume
        target: /var/lib/postgresql/data/
    ports:
      - "${PG_HOST_PORT}:5432"
    networks:
      - backend

  web:
    image: ${COMPOSE_PROJECT_NAME}_web_dev
    container_name: ${COMPOSE_PROJECT_NAME}_web_dev
    depends_on:
      - postgres
    build:
      dockerfile: ./docker/dev/web/Dockerfile
      context: .
    restart: always
    tty: true
    env_file:
      - .env
      - dev.env
    volumes:
      - .:/code/
    ports:
      - "8003:8003"
      - "8890:8890"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_volume:
