name: Pre-commit Auto-Update

on:
  schedule:
  - cron: "0 0 * * *"   # Run every day at midnight
  workflow_dispatch:    # To trigger manually

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2.1.1
      with:
        python-version: 3.8

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run pre-commit autoupdate
      working-directory: .
      run: pre-commit autoupdate

    - name: Only account for changes in pre-commit-config.yaml file
      run: |
        cat .gitignore > .tmpgitignore
        true > .gitignore
        echo !.pre-commit-config.yaml >> .gitignore

    - name: Create PR
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update/pre-commit-autoupdate
        title: Auto-update pre-commit hooks
        commit-message: Auto-update pre-commit hooks
        body: Update tools in pre-commit config to latest versions.
        labels:  dependencies, ci
        reviewers: WayneLambert
        assignees: WayneLambert
