name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 10
          stale-issue-label: "Stale Issue"
          stale-issue-message: >
            This issue is stale since it has been open for 10 days without any activity. If the
            'Stale Issue' label hasn't been removed or a comment made on the issue, it will be
            closed after 5 days of inactivity.
          days-before-close: 5

          stale-pr-label: "Stale PR"
          stale-pr-message: "Stale pull request message"
          
