name: Test

on:
  push:
    branches:
      - ci

jobs:

  test:
    name: Run Django Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: 'refs/heads/ci'

      - name: Debug Script
        uses: hmarr/debug-action@v1.0.0

      - name: Set up Python 3.8.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.5

      - name: Add Environment Variables to .env file
        run: |
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo DJANGO_PROJECT_NAME=${{ secrets.DJANGO_PROJECT_NAME }} >> .env
          echo DJANGO_ADMIN_LOGIN_PATH=${{ secrets.DJANGO_ADMIN_LOGIN_PATH }} >> .env
          echo COMPOSE_PROJECT_NAME=${{ secrets.COMPOSE_PROJECT_NAME }} >> .env
          echo COMPOSE_HTTP_TIMEOUT=120 >> .env
          echo DATABASE=${{ secrets.DATABASE }} >> .env

          # ... and variables within the project's `.dev.env` file
          echo DJANGO_SETTINGS_MODULE=${{ secrets.DJANGO_SETTINGS_MODULE }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DB_PASS=${{ secrets.DB_PASS }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env

      - name: Set Environment Variables
        run: for var in `cat .env` ; do echo "::set-env name=${var%%=*}::${var##*=}" ; done

      - name: Install pipenv
        run: python -m pip install pipenv

      - name: Install dependencies
        run: pipenv install --system --ignore-pipfile --deploy --dev

      - name: Run tests
        run: pytest --cov=./ --cov-report=xml
        env:
          SYSTEM_ENV: GITHUB_WORKFLOW
