name: Test and Coverage Reporting

on:
  push:
    branches:
      - ci

jobs:
  test:
    name: Test and Coverage Reporting Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Debug Script
        uses: hmarr/debug-action@v1.0.0

      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install PipEnv
        uses: dschep/install-pipenv-action@v1
        with:
          version: 2020.6.2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --system --ignore-pipfile --deploy --dev

      - name: Set Environment variables
        run: echo "Setting environment variables"
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Run Tests and Generate Coverage Report
        run: |
          pytest --cov=./ --cov-report=xml

      - name: Upload Coverage Report to Codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
